# Generated by Django 4.2.7 on 2023-12-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trip_from', models.CharField(max_length=200)),
                ('trip_to', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=200)),
                ('data', models.DateField(verbose_name='data of trip')),
                ('phone', models.IntegerField(default=0, verbose_name='Client phone number')),
                ('count_of_passengers', models.IntegerField(default=0, verbose_name='Count of passengers')),
                ('desc', models.CharField(max_length=200)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=0)),
                ('photos', models.ImageField(upload_to='car_photos/')),
                ('information', models.CharField(max_length=200)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('photo', models.ImageField(upload_to='driver_photos/')),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('response', models.CharField(max_length=200)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('day_start', models.CharField(max_length=200)),
                ('day_finish', models.CharField(max_length=200)),
                ('time_start', models.CharField(max_length=200)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
