# Generated by Django 4.2.7 on 2023-12-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking_cars_driver_response_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='cities_list',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
